/* tslint:disable */
/* eslint-disable */
/**
 * Preference public API
 * Preference public API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BadRequestError
 */
export interface BadRequestError {
  /**
   * List of error messages
   * @type {Array<string>}
   * @memberof BadRequestError
   */
  messages?: Array<string>;
}

/**
 * Check if a given object implements the BadRequestError interface.
 */
export function instanceOfBadRequestError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function BadRequestErrorFromJSON(json: any): BadRequestError {
  return BadRequestErrorFromJSONTyped(json, false);
}

export function BadRequestErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BadRequestError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    messages: !exists(json, "messages") ? undefined : json["messages"],
  };
}

export function BadRequestErrorToJSON(value?: BadRequestError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    messages: value.messages,
  };
}
