/* tslint:disable */
/* eslint-disable */
/**
 * Preference public API
 * Preference public API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieAllOf
 */
export interface MovieAllOf {
    /**
     * Movie unique identifier
     * @type {number}
     * @memberof MovieAllOf
     */
    id: number;
}

/**
 * Check if a given object implements the MovieAllOf interface.
 */
export function instanceOfMovieAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function MovieAllOfFromJSON(json: any): MovieAllOf {
    return MovieAllOfFromJSONTyped(json, false);
}

export function MovieAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function MovieAllOfToJSON(value?: MovieAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

